import Navbar from '@/components/Navbar/Navbar';
import './globals.css';
import { ThemeProvider } from './providers/ThemeProvider';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider>
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

export const fetchCache = 'default-cache';
